<div class="d-flex justify-content-end gap-3 mb-3">
    <button id="btnRelatorio" class="btn fw-bold text-white"
            style="background: #e07503 !important; border: none;">
        <i class="fa fa-file-pdf me-2"></i> Gerar Relatório
    </button>

    <button type="button" id="btnRegister" class="btn fw-bold text-white"
            style="background: #e07503 !important; border: none;">
        <i class="fas fa-plus me-2"></i> Novo Livro
    </button>
</div>
