<nav class="navbar navbar-expand-lg navbar-light  py-3">
    <div class="container px-5">
        <a class="navbar-brand" style="color: #e07503 !important;"><span class="  fw-bolder ">
                <i class="fas fa-book  me-2"></i>Livro Esfera</span></a>
        <button id="toggleMode" class="btn btn-outline-secondary">
            <i class="fas fa-moon"></i>
        </button>
    </div>
</nav>