<nav class="navbar navbar-expand-lg navbar-light  py-3">
    <div class="container px-5">
        <a class="navbar-brand" href="index.html"><span class="fw-bolder text-primary">
                <i class="fas fa-book text-primary me-2"></i>Livro Esfera</span></a>
        <button id="toggleMode" class="btn btn-outline-secondary">
            <i class="fas fa-moon"></i>
        </button>

        <!--        <div class="navbar-collapse collapse" id="navbarSupportedContent" style="">-->
        <!--            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">-->
        <!--                <li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>-->
        <!--                <li class="nav-item"><a class="nav-link" href="resume.html">Resume</a></li>-->
        <!--                <li class="nav-item"><a class="nav-link" href="projects.html">Projects</a></li>-->
        <!--                <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>-->
        <!--            </ul>-->
        <!--        </div>-->
    </div>
</nav>



