<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Livro Esfera')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/datatables.min.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/theme.css'))
    ?>

    <?= $this->headScript() ?>
</head>
<body>

<?= $this->partial('layout/template/nav'); ?>
<?= $this->partial('layout/template/loader'); ?>

<?= $this->content ?>

<?= $this->partial('layout/template/footer'); ?>

<?= $this->inlineScript()->prependFile($this->basePath('js/bundle.js')) ?>

</body>
</html>