<div class="container my-5" id="livro-cadastro">
    <form id="formLivro" >
        <div class="row mb-3">
            <div class="col-12 col-md-6 mb-3">
                <label class="form-label fw-bold" for="tituloLivro"><i class="fas fa-book text-dark me-2"></i> Título</label>
                <input type="text" id="tituloLivro" name="titulo" class="form-control" required>
            </div>

            <div class="col-12 col-md-6 mb-3">
                <label class="form-label fw-bold" for="editoraLivro"><i class="fas fa-building text-dark me-2"></i> Editora</label>
                <input type="text" id="editoraLivro" name="editora" class="form-control" required>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12 col-md-4 mb-3">
                <label class="form-label fw-bold" for="anoPublicacao"><i class="fas fa-calendar-alt text-dark me-2"></i> Ano</label>
                <input type="number" id="anoPublicacao" name="ano_publicacao" class="form-control" required>
            </div>

            <div class="col-12 col-md-4 mb-3">
                <label class="form-label fw-bold" for="valorLivro"><i class="fas fa-dollar-sign text-dark me-2"></i> Valor</label>
                <input type="number" step="0.01" id="valorLivro" name="valor" class="form-control" required>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12 col-md-6 mb-3">
                <label class="form-label fw-bold" for="autorLivro"><i class="fas fa-user-alt text-dark me-2"></i> Autor</label>
                <input type="text" id="autorLivro" name="autor" class="form-control" required>
            </div>

            <div class="col-12 col-md-6 mb-3">
                <label class="form-label fw-bold" for="assuntoLivro"><i class="fas fa-tags text-dark me-2"></i> Assunto</label>
                <input type="text" id="assuntoLivro" name="assunto" class="form-control" required>
            </div>
        </div>

        <div class="d-flex justify-content-end">
            <button id="btnSalvar" type="button" class="btn btn-dark">
                <i class="fas fa-save me-2"></i> Salvar
            </button>
        </div>
    </form>
</div>
