<div class="my-5 container" id="livro-hide">
    <div class="card shadow rounded-4">
        <div class="card-header text-white py-3" style="background-color: #192635;">
            <h3 class="mb-0 fw-bold">
                📖 Lista de Livros
            </h3>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table id="myTable" class="table table-hover table-striped table-bordered align-middle">
                    <thead class="bg-dark text-white text-center">
                    <tr>
                        <th>Título</th>
                        <th>Autor</th>
                        <th>Assunto</th>
                        <th>Editora</th>
                        <th>Publicado</th>
                        <th>Valor</th>
                        <th>Ação</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<style>
    table thead th {
        background-color: #192635 !important;
        color: #ffffff !important;
        text-align: center;
        vertical-align: middle;
    }

    table tbody tr:hover {
        background-color: #f0f4f8;
    }
</style>