<div class="my-5" id="livro-hide">

    <div class="card-header">
        <h1 class="">📚 Lista de Livros</h1>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table id="myTable" class="table table-bordered table-hover table-striped align-middle" width="100%">
                <thead class="table-dark text-center">
                <tr>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody class="text-center">
                </tbody>
                <tfoot class="table-light text-center fw-bold">

                </tfoot>
            </table>
        </div>
    </div>
</div>